{% set name = "trailscraper" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trailscraper-{{ version }}.tar.gz
  sha256: 8aade831f331d5f3b3780478473c4dbe45dc2018026df0112624cd37bbdc3605

build:
  number: 0
  noarch: python
  entry_points:
    - trailscraper=trailscraper.cli:root_group
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - boto3 ==1.17.62
    - click ==7.1.2
    - toolz ==0.11.1
    - dateparser ==1.0.0
    - pytz ==2021.1
    # - ruamel.yaml ==0.17.4

test:
  imports:
    - trailscraper
  commands:
    - pip check
    - trailscraper --help
  requires:
    - pip

about:
  home: http://github.com/flosell/trailscraper
  summary: A command-line tool to get valuable information out of AWS CloudTrail
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
