{% set name = "trailscraper" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trailscraper-{{ version }}.tar.gz
  sha256: b0ae6be8013226943a6db068420fef8c537c0061cb1e36528b05896aa9326393

build:
  number: 0
  noarch: python
  entry_points:
    - trailscraper=trailscraper.cli:root_group
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - boto3 ==1.26.22
    - click ==8.1.3
    - toolz ==0.12.0
    - dateparser ==1.1.4
    - pytz ==2022.6
    - ruamel.yaml ==0.17.21

test:
  imports:
    - trailscraper
  commands:
    - pip check
    - trailscraper --help
  requires:
    - pip

about:
  home: http://github.com/flosell/trailscraper
  summary: A command-line tool to get valuable information out of AWS CloudTrail
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
