{% set name = "trailscraper" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trailscraper-{{ version }}.tar.gz
  sha256: 96278fcd08aba2c684cad5e73972149d3f756ef52f146532440793ddcbbf9230

build:
  number: 0
  noarch: python
  entry_points:
    - trailscraper=trailscraper.cli:root_group
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - boto3 ==1.37.9
    - click ==8.1.8
    - toolz ==1.0.0
    - dateparser ==1.2.1
    - pytz ==2025.1
    - ruamel.yaml ==0.18.10

test:
  imports:
    - trailscraper
  commands:
    - pip check
    - trailscraper --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/flosell/trailscraper
  summary: A command-line tool to get valuable information out of AWS CloudTrail
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
